### PR TITLE
Chore add pre commit and formatter (black)

### PR DESCRIPTION
**Pull request by chozandrias76**
I noticed there was no formatter added to the project. I wanted to start contributing, but I didn't want to interfere with any styling. Does this work for you?

### CODE REVIEW

**Comment by Ariescyn** [comment]
Wow thanks for your work! Looks good and I'll merge it shortly. If you didn't care about interfering with styling, what changes would you want to make?

**Comment by VinegarLove** [comment]
@chozandrias76 I understand that a standard format is a good thing but

1. TK interface is a mess written with the formatter. It spits a lot of lines and everything becomes unreadable
2. The project use (mostly) the apostrophe for string and at this point we should keep that. We can set that in the formatter so we don't have to change the whole file (we miss all the github history doing that).

**Comment by Ariescyn** [comment]
I'm guessing you add your interpreter in the yaml? I replaced python_spec='python3.8' with my version 3.10.2 otherwise i get RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.8'

Let's do single quotes as VinegarLove said. I don't know how to config the formatter so ill let you do it. After that i would like to merge so i can work on the bug-fix

**Comment by VinegarLove** [comment]
I think the python version shouldn't be specified or fixed at a version at all...
Every users could have a different version and they would have to modify the file if they want to make changes. If possible remove the hardcoded version. I don't know how the formatter works, but blocking other versions doesn't seem a good idea.

**Comment by quasarj** [comment]
Not sure Black allows using single quotes, though it looks like it has -S which will skip string normalization altogether. This project doesn't really have enough history to worry about swapping quotes, does it?

**Pull request merged**
